[project]
name = "Ledger"
version = "0.1.0"
description = "A payment processing gateway"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic",
    "asgi-lifespan",
    "asyncpg",
    "authlib",
    "celery",
    "fastapi[all]",
    "fastapi-limiter",
    "gevent",
    "psycopg",
    "psycopg2",
    "pwdlib[argon2]",
    "pydantic-settings",
    "pyrate-limiter",
    "pytest",
    "pytest-asyncio",
    "python-jose",
    "redis",
    "resend",
    "sentry-sdk",
    "sqlalchemy",
    "paystack-sdk>=1.0.1",
]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope= "session"
asyncio_default_test_loop_scope= "session"
