"""migrate_003

Revision ID: 56b8c7e459d9
Revises: f8565f70861a
Create Date: 2026-09-19 18:31:43.544967

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '56b8c7e459d9'
down_revision: Union[str, Sequence[str], None] = 'f8565f70861a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_auth_codes_wallet_id'), table_name='authorization_codes')
    op.drop_index(op.f('idx_auth_otp'), table_name='otp')
    op.drop_index(op.f('idx_outbox_status_event_type'), table_name='outbox')
    op.create_index('idx_outbox_status', 'outbox', ['status'], unique=False)
    op.drop_index(op.f('idx_payment_transactions_paystack_reference'), table_name='payment_transactions')
    op.drop_index(op.f('idx_payment_transactions_status_id'), table_name='payment_transactions')
    op.drop_index(op.f('idx_payment_transactions_wallet_id'), table_name='payment_transactions')
    op.drop_constraint(op.f('payment_transactions_user_id_key'), 'payment_transactions', type_='unique')
    op.drop_index(op.f('idx_payment_transactions_user_id'), table_name='payment_transactions')
    op.create_index('idx_payment_transactions_user_id', 'payment_transactions', ['user_id'], unique=False)
    op.create_index('idx_payment_transactions_status', 'payment_transactions', ['status'], unique=False)
    op.drop_index(op.f('idx_refund_state_events_occurred_at'), table_name='refund_state_events')
    op.drop_index(op.f('idx_refund_state_events_refund_id'), table_name='refund_state_events')
    op.create_index('idx_refund_state_events_refund_id', 'refund_state_events', ['refund_id'], unique=False)
    op.drop_index(op.f('idx_refunds_composite'), table_name='refunds')
    op.drop_index(op.f('idx_refunds_payment_transaction_id_&_id'), table_name='refunds')
    op.create_index('idx_refunds_payment_transaction_id', 'refunds', ['payment_transaction_id'], unique=False)
    op.create_index('idx_refunds_user_id', 'refunds', ['user_id'], unique=False)
    op.drop_index(op.f('idx_transaction_state_events_occurred_at'), table_name='transaction_state_events')
    op.drop_index(op.f('idx_transaction_state_events_single_row_state'), table_name='transaction_state_events')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_google_email'), table_name='users')
    op.drop_index(op.f('idx_wallet_credits_payment_transaction_id'), table_name='wallet_credits')
    op.drop_index(op.f('idx_wallet_credits_wallet_id'), table_name='wallet_credits')
    op.create_index('idx_wallet_credits_wallet_id', 'wallet_credits', ['wallet_id'], unique=False)
    op.drop_index(op.f('idx_wallets_user_id'), table_name='wallets')
    op.drop_constraint(op.f('webhook_events_paystack_data_id_key'), 'webhook_events', type_='unique')
    op.drop_constraint(op.f('webhook_events_paystack_reference_key'), 'webhook_events', type_='unique')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('webhook_events_paystack_reference_key'), 'webhook_events', ['paystack_reference'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('webhook_events_paystack_data_id_key'), 'webhook_events', ['paystack_data_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_wallets_user_id'), 'wallets', ['user_id', 'id'], unique=True)
    op.drop_index('idx_wallet_credits_wallet_id', table_name='wallet_credits')
    op.create_index(op.f('idx_wallet_credits_wallet_id'), 'wallet_credits', ['wallet_id', 'id'], unique=False)
    op.create_index(op.f('idx_wallet_credits_payment_transaction_id'), 'wallet_credits', ['payment_transaction_id'], unique=True)
    op.create_index(op.f('idx_users_google_email'), 'users', ['google_email'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_transaction_state_events_single_row_state'), 'transaction_state_events', ['transaction_id', 'status'], unique=False)
    op.create_index(op.f('idx_transaction_state_events_occurred_at'), 'transaction_state_events', ['occurred_at'], unique=False)
    op.drop_index('idx_refunds_user_id', table_name='refunds')
    op.drop_index('idx_refunds_payment_transaction_id', table_name='refunds')
    op.create_index(op.f('idx_refunds_payment_transaction_id_&_id'), 'refunds', ['payment_transaction_id', 'id'], unique=False)
    op.create_index(op.f('idx_refunds_composite'), 'refunds', ['user_id', 'id', 'status'], unique=False)
    op.drop_index('idx_refund_state_events_refund_id', table_name='refund_state_events')
    op.create_index(op.f('idx_refund_state_events_refund_id'), 'refund_state_events', ['refund_id', 'status'], unique=False)
    op.create_index(op.f('idx_refund_state_events_occurred_at'), 'refund_state_events', ['occurred_at'], unique=False)
    op.drop_index('idx_payment_transactions_status', table_name='payment_transactions')
    op.drop_index('idx_payment_transactions_user_id', table_name='payment_transactions')
    op.create_index(op.f('idx_payment_transactions_user_id'), 'payment_transactions', ['user_id', 'id'], unique=False)
    op.create_unique_constraint(op.f('payment_transactions_user_id_key'), 'payment_transactions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_payment_transactions_wallet_id'), 'payment_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('idx_payment_transactions_status_id'), 'payment_transactions', ['status', 'id'], unique=True)
    op.create_index(op.f('idx_payment_transactions_paystack_reference'), 'payment_transactions', ['paystack_reference'], unique=True)
    op.drop_index('idx_outbox_status', table_name='outbox')
    op.create_index(op.f('idx_outbox_status_event_type'), 'outbox', ['status', 'event_type'], unique=False)
    op.create_index(op.f('idx_auth_otp'), 'otp', ['otp'], unique=False)
    op.create_index(op.f('idx_auth_codes_wallet_id'), 'authorization_codes', ['wallet_id', 'code'], unique=True)
    # ### end Alembic commands ###
