"""migrate_005

Revision ID: 5a80cdcb6d22
Revises: b084734480c5
Create Date: 2026-09-21 10:09:03.491656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a80cdcb6d22'
down_revision: Union[str, Sequence[str], None] = 'b084734480c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('authorization_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'authorization_url')
    # ### end Alembic commands ###
