"""migration_001

Revision ID: 7c19a0bab701
Revises: 1cc78c8b43c1
Create Date: 2026-09-17 16:25:03.775778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c19a0bab701'
down_revision: Union[str, Sequence[str], None] = '1cc78c8b43c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processed_email', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'failed', name='emailstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name='emails_pk')
    )
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'processing', name='outboxenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name='outbox_pk')
    )
    op.create_index('idx_outbox_status_event_type', 'outbox', ['status', 'event_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('type', sa.Enum('email', 'google', name='usertype'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('google_email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pk'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_google_email', 'users', ['google_email'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('paystack_data_id', sa.BigInteger(), nullable=True),
    sa.Column('paystack_reference', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name='webhook_events_pk'),
    sa.UniqueConstraint('paystack_data_id'),
    sa.UniqueConstraint('paystack_reference')
    )
    op.create_index('idx_webhook_events_dedup_comp', 'webhook_events', ['paystack_data_id', 'paystack_reference', 'event_type'], unique=True)
    op.create_table('otp',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('valid', 'used', name='otpstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='otp_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='otp_id_pk'),
    sa.UniqueConstraint('otp')
    )
    op.create_index('idx_auth_otp', 'otp', ['otp'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('NGN', name='currencyenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallets_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wallets_pk'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_wallets_user_id', 'wallets', ['user_id', 'id'], unique=True)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('paystack_reference', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('NGN', name='currencyenum'), nullable=False),
    sa.Column('channel', sa.Enum('card', 'bank_transfer', name='channelenum'), nullable=False),
    sa.Column('status', sa.Enum('failed', 'queued', 'pending', 'ongoing', 'success', 'rejected', 'reversed', 'initiated', 'abandoned', 'processing', name='transactionstatus'), nullable=False),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('authorization_code', sa.Text(), nullable=True),
    sa.Column('bank_transfer_account_number', sa.Text(), nullable=True),
    sa.Column('card_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wallet_credited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payment_transactions_user_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='payment_transactions_wallet_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payment_transactions_pk'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('paystack_reference'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_payment_transactions_created_at', 'payment_transactions', ['created_at'], unique=False)
    op.create_index('idx_payment_transactions_paystack_reference', 'payment_transactions', ['paystack_reference'], unique=True)
    op.create_index('idx_payment_transactions_status_id', 'payment_transactions', ['status', 'id'], unique=True)
    op.create_index('idx_payment_transactions_updated_at', 'payment_transactions', ['updated_at'], unique=False)
    op.create_index('idx_payment_transactions_user_id', 'payment_transactions', ['user_id', 'id'], unique=False)
    op.create_index('idx_payment_transactions_wallet_id', 'payment_transactions', ['wallet_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_transaction_id', sa.UUID(), nullable=False),
    sa.Column('paystack_refund_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('NGN', name='currencyenum'), nullable=False),
    sa.Column('status', sa.Enum('failed', 'pending', 'processed', 'initiated', 'processing', 'needs_attention', name='refundstatus'), nullable=False),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('merchant_note', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wallet_debited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], name='wallet_credits_payment_transaction_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refunds_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refunds_pk'),
    sa.UniqueConstraint('paystack_refund_id')
    )
    op.create_index('idx_refunds_composite', 'refunds', ['user_id', 'id', 'status'], unique=False)
    op.create_index('idx_refunds_created_at', 'refunds', ['created_at'], unique=False)
    op.create_index('idx_refunds_payment_transaction_id_&_id', 'refunds', ['payment_transaction_id', 'id'], unique=False)
    op.create_index('idx_refunds_updated_at', 'refunds', ['updated_at'], unique=False)
    op.create_table('transaction_state_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('failed', 'queued', 'pending', 'ongoing', 'success', 'rejected', 'reversed', 'initiated', 'abandoned', 'processing', name='transactionstatus'), nullable=False),
    sa.Column('source', sa.Enum('webhook', 'user_action', 'reconciliation', name='sourceenum'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], name='state_transaction_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='transaction_state_events_pk')
    )
    op.create_index('idx_transaction_state_events_occurred_at', 'transaction_state_events', ['occurred_at'], unique=False)
    op.create_index('idx_transaction_state_events_single_row_state', 'transaction_state_events', ['transaction_id', 'status'], unique=False)
    op.create_index('idx_transaction_state_events_transaction_id', 'transaction_state_events', ['transaction_id'], unique=False)
    op.create_table('wallet_credits',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('payment_transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], name='wallet_credits_payment_transaction_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='wallet_credits_wallet_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wallet_credits_pk'),
    sa.UniqueConstraint('payment_transaction_id')
    )
    op.create_index('idx_wallet_credits_created_at', 'wallet_credits', ['created_at'], unique=False)
    op.create_index('idx_wallet_credits_payment_transaction_id', 'wallet_credits', ['payment_transaction_id'], unique=True)
    op.create_index('idx_wallet_credits_wallet_id', 'wallet_credits', ['wallet_id', 'id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wallet_credits_wallet_id', table_name='wallet_credits')
    op.drop_index('idx_wallet_credits_payment_transaction_id', table_name='wallet_credits')
    op.drop_index('idx_wallet_credits_created_at', table_name='wallet_credits')
    op.drop_table('wallet_credits')
    op.drop_index('idx_transaction_state_events_transaction_id', table_name='transaction_state_events')
    op.drop_index('idx_transaction_state_events_single_row_state', table_name='transaction_state_events')
    op.drop_index('idx_transaction_state_events_occurred_at', table_name='transaction_state_events')
    op.drop_table('transaction_state_events')
    op.drop_index('idx_refunds_updated_at', table_name='refunds')
    op.drop_index('idx_refunds_payment_transaction_id_&_id', table_name='refunds')
    op.drop_index('idx_refunds_created_at', table_name='refunds')
    op.drop_index('idx_refunds_composite', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('idx_payment_transactions_wallet_id', table_name='payment_transactions')
    op.drop_index('idx_payment_transactions_user_id', table_name='payment_transactions')
    op.drop_index('idx_payment_transactions_updated_at', table_name='payment_transactions')
    op.drop_index('idx_payment_transactions_status_id', table_name='payment_transactions')
    op.drop_index('idx_payment_transactions_paystack_reference', table_name='payment_transactions')
    op.drop_index('idx_payment_transactions_created_at', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('idx_wallets_user_id', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('idx_auth_otp', table_name='otp')
    op.drop_table('otp')
    op.drop_index('idx_webhook_events_dedup_comp', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('idx_users_google_email', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_outbox_status_event_type', table_name='outbox')
    op.drop_table('outbox')
    op.drop_table('emails')
    # ### end Alembic commands ###
