"""migrate_004

Revision ID: b084734480c5
Revises: 56b8c7e459d9
Create Date: 2026-09-20 22:38:24.798093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b084734480c5'
down_revision: Union[str, Sequence[str], None] = '56b8c7e459d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

wallet_credit_type = postgresql.ENUM('credit', 'debit', name='walletcredittype')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    wallet_credit_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'wallet_credits',
        sa.Column(
            'type',
            wallet_credit_type,
            nullable=False,
            # existing rows predate the credit/debit split - they were all
            # funding credits, so backfill them as such
            server_default='credit',
        ),
    )
    op.alter_column('wallet_credits', 'type', server_default=None)
    op.drop_constraint(op.f('wallet_credits_payment_transaction_id_key'), 'wallet_credits', type_='unique')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('wallet_credits_payment_transaction_id_key'), 'wallet_credits', ['payment_transaction_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('wallet_credits', 'type')
    wallet_credit_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
