"""migrate_002

Revision ID: f8565f70861a
Revises: 7c19a0bab701
Create Date: 2026-09-18 12:17:47.270241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8565f70861a'
down_revision: Union[str, Sequence[str], None] = '7c19a0bab701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('exp_month', sa.Text(), nullable=False),
    sa.Column('exp_year', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('card', 'bank_transfer', name='channelenum'), nullable=False),
    sa.Column('card_type', sa.Text(), nullable=False),
    sa.Column('country_code', sa.Text(), nullable=False),
    sa.Column('reusable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='auth_codes_wallet_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='auth_codes_pk'),
    sa.UniqueConstraint('wallet_id')
    )
    op.create_index('idx_auth_codes_wallet_id', 'authorization_codes', ['wallet_id', 'code'], unique=True)
    op.create_table('refund_state_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('refund_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('failed', 'pending', 'processed', 'initiated', 'processing', 'needs_attention', name='refundstatus'), nullable=False),
    sa.Column('source', sa.Enum('webhook', 'user_action', 'reconciliation', name='sourceenum'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], name='state_refund_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refund_state_events_pk')
    )
    op.create_index('idx_refund_state_events_occurred_at', 'refund_state_events', ['occurred_at'], unique=False)
    op.create_index('idx_refund_state_events_refund_id', 'refund_state_events', ['refund_id', 'status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_refund_state_events_refund_id', table_name='refund_state_events')
    op.drop_index('idx_refund_state_events_occurred_at', table_name='refund_state_events')
    op.drop_table('refund_state_events')
    op.drop_index('idx_auth_codes_wallet_id', table_name='authorization_codes')
    op.drop_table('authorization_codes')
    # ### end Alembic commands ###
